hetzner:
    api_token: 1k6pJujITm16RuADHrzjkYeIjq7lzFbTSUBDkAPDYif0YFu4j1rvhoWniowX8SLL
    server_type: cpx21
    location: fsn1
    volume_size: 10
docker:
    socket_path: /var/run/docker.sock
    proxy_port: 2376
keepalive:
    interval: 30s
    timeout: 5m0s
    retry_interval: 5s
    max_retries: 3
ssh:
    key_path: ~/.ssh/id_rsa
    port: 22
    timeout: 60s
    keep_alive: 30s
logging:
    level: debug
    format: json
    output: stdout